# Generated by Django 4.1 on 2022-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
    ]
