# Generated by Django 4.1 on 2022-08-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ability_en',
            field=models.TextField(default='-', verbose_name='Способность-англ'),
        ),
        migrations.AddField(
            model_name='card',
            name='ability_ru',
            field=models.TextField(default='-', verbose_name='Способность-рус'),
        ),
        migrations.AddField(
            model_name='card',
            name='artist',
            field=models.CharField(default='-', max_length=50, verbose_name='Художник'),
        ),
        migrations.AddField(
            model_name='card',
            name='atk',
            field=models.IntegerField(default=0, verbose_name='ATK'),
        ),
        migrations.AddField(
            model_name='card',
            name='atk_type',
            field=models.CharField(default='-', max_length=50, verbose_name='Тип ATK'),
        ),
        migrations.AddField(
            model_name='card',
            name='block',
            field=models.IntegerField(default=0, verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='card',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='card',
            name='class_card',
            field=models.CharField(default='-', max_length=50, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='card',
            name='def_card',
            field=models.IntegerField(default=0, verbose_name='БРН'),
        ),
        migrations.AddField(
            model_name='card',
            name='faction',
            field=models.CharField(default='-', max_length=50, verbose_name='Фракция'),
        ),
        migrations.AddField(
            model_name='card',
            name='faq_en',
            field=models.TextField(default='-', verbose_name='Примечание-англ'),
        ),
        migrations.AddField(
            model_name='card',
            name='faq_ru',
            field=models.TextField(default='-', verbose_name='Примечание-рус'),
        ),
        migrations.AddField(
            model_name='card',
            name='fluff_en',
            field=models.TextField(default='-', verbose_name='ХудожественныйТекст-англ'),
        ),
        migrations.AddField(
            model_name='card',
            name='fluff_ru',
            field=models.TextField(default='-', verbose_name='ХудожественныйТекст-рус'),
        ),
        migrations.AddField(
            model_name='card',
            name='health',
            field=models.IntegerField(default=0, verbose_name='Здоровье'),
        ),
        migrations.AddField(
            model_name='card',
            name='legality_block',
            field=models.CharField(default='-', max_length=50, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='card',
            name='legality_classic',
            field=models.CharField(default='-', max_length=50, verbose_name='Classic'),
        ),
        migrations.AddField(
            model_name='card',
            name='legality_contemporary',
            field=models.CharField(default='-', max_length=50, verbose_name='Contemporary'),
        ),
        migrations.AddField(
            model_name='card',
            name='legality_core',
            field=models.CharField(default='-', max_length=50, verbose_name='Core'),
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity_en',
            field=models.CharField(default='-', max_length=50, verbose_name='Редкость-англ'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity_ru',
            field=models.CharField(default='-', max_length=50, verbose_name='Редкость-рус'),
        ),
        migrations.AddField(
            model_name='card',
            name='released',
            field=models.CharField(default='-', max_length=20, verbose_name='Дата выпуска'),
        ),
        migrations.AddField(
            model_name='card',
            name='set_en',
            field=models.CharField(default='-', max_length=50, verbose_name='Выпуск-англ'),
        ),
        migrations.AddField(
            model_name='card',
            name='set_ru',
            field=models.CharField(default='-', max_length=50, verbose_name='Выпуск-рус'),
        ),
        migrations.AddField(
            model_name='card',
            name='strike_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость удара'),
        ),
        migrations.AddField(
            model_name='card',
            name='type_en',
            field=models.CharField(default='-', max_length=100, verbose_name='Тип-англ'),
        ),
        migrations.AddField(
            model_name='card',
            name='type_ru',
            field=models.CharField(default='-', max_length=100, verbose_name='Тип-рус'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name_en',
            field=models.CharField(default='-', max_length=50, verbose_name='Имя-англ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name_ru',
            field=models.CharField(default='-', max_length=50, verbose_name='Имя-рус'),
        ),
    ]
