# Generated by Django 4.1 on 2022-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_ability_en_card_ability_ru_card_artist_card_atk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
            ],
        ),
    ]
